export const localFallbackProjects = [
  {
    id: "techmdbd",
    title: "TECHMDBD",
    category: "Web Design",
    description: "A futuristic tech platform for PC building, product comparison, and tech content.",
    tech: ["Next.js", "Tailwind CSS", "Firebase", "MongoDB"],
    image: "",
    imageUrl: "",
    link: "#",
    projectUrl: "#",
    github: "#",
    githubUrl: "#",
    delay: 0.1
  },
  {
    id: "ai-chat",
    title: "AI Chat Application",
    category: "AI Tools",
    description: "A modern AI-powered chat platform with futuristic UI and intelligent automation features.",
    tech: ["React", "Node.js", "OpenAI API"],
    image: "",
    imageUrl: "",
    link: "#",
    projectUrl: "#",
    github: "#",
    githubUrl: "#",
    delay: 0.2
  },
  {
    id: "portfolio-website",
    title: "Portfolio Website",
    category: "UI/UX",
    description: "A cinematic personal portfolio with smooth animations and luxury futuristic design.",
    tech: ["Next.js", "Framer Motion", "Tailwind CSS"],
    image: "",
    imageUrl: "",
    link: "#",
    projectUrl: "#",
    github: "#",
    githubUrl: "#",
    delay: 0.3
  },
  {
    id: "minecraft-dashboard",
    title: "Minecraft Server Dashboard",
    category: "Full Stack",
    description: "A custom server management dashboard for Minecraft hosting and real-time server control.",
    tech: ["React", "Firebase", "Express.js"],
    image: "",
    imageUrl: "",
    link: "#",
    projectUrl: "#",
    github: "#",
    githubUrl: "#",
    delay: 0.4
  },
  {
    id: "esp8266-wifi",
    title: "ESP8266 WiFi Control Panel",
    category: "Full Stack",
    description: "A smart WiFi management interface for ESP8266 devices with modern responsive UI.",
    tech: ["HTML", "CSS", "JavaScript"],
    image: "",
    imageUrl: "",
    link: "#",
    projectUrl: "#",
    github: "#",
    githubUrl: "#",
    delay: 0.5
  },
  {
    id: "ai-automation-system",
    title: "AI Automation System",
    category: "AI Tools",
    description: "An intelligent workflow automation system with chatbot integration and task management.",
    tech: ["Node.js", "Firebase", "AI APIs"],
    image: "",
    imageUrl: "",
    link: "#",
    projectUrl: "#",
    github: "#",
    githubUrl: "#",
    delay: 0.6
  }
];
